version: '3.7'
services:
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./redis-data:/data
    entrypoint: redis-server --appendonly yes
    ports:
      - "63790:6379"
  postgresdb:
    image: postgres:12-alpine
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres-data:/var/lib/postgresql/data
