# Generated by Django 3.0.3 on 2020-03-18 15:04

from django.conf import settings
import django.contrib.postgres.search
from django.db import migrations, models
import django.db.models.deletion
import miller.fields
import miller.models.document


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('miller', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
        migrations.AddField(
            model_name='document',
            name='attachment',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=miller.models.document.attachment_file_name),
        ),
        migrations.AddField(
            model_name='document',
            name='copyrights',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='data',
            field=miller.fields.UTF8JSONField(blank=True, default=dict, help_text='JSON format', verbose_name='data contents'),
        ),
        migrations.AddField(
            model_name='document',
            name='documents',
            field=models.ManyToManyField(blank=True, related_name='_document_documents_+', to='miller.Document'),
        ),
        migrations.AddField(
            model_name='document',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='mimetype',
            field=models.CharField(blank=True, default='', max_length=127),
        ),
        migrations.AddField(
            model_name='document',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='short_url',
            field=models.CharField(blank=True, db_index=True, max_length=22, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.CharField(blank=True, db_index=True, max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='document',
            name='snapshot',
            field=models.FileField(blank=True, max_length=200, null=True, upload_to=miller.models.document.snapshot_attachment_file_name),
        ),
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('bibtex', 'bibtex'), ('crossref', 'bibtex'), ('video-cover', 'video interview'), ('video', 'video'), ('text', 'text'), ('picture', 'picture'), ('pdf', 'pdf'), ('image', 'image'), ('photo', 'photo'), ('rich', 'rich'), ('link', 'link'), ('audiovisual', 'audiovisual'), ('entity', 'entity: see data type property')], max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='data',
            field=miller.fields.UTF8JSONField(blank=True, default=dict, help_text='JSON format', verbose_name='metadata contents'),
        ),
    ]
