# Generated by Django 3.0.7 on 2020-06-04 08:53

from django.db import migrations, models
import miller.models.document


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0002_auto_20200526_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='short_url',
            field=models.CharField(blank=True, db_index=True, default=miller.models.document.create_short_url, max_length=22, unique=True),
        ),
    ]
