# Generated by Django 3.0.7 on 2020-06-08 18:07

from django.db import migrations
import miller.fields


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0005_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='data',
            field=miller.fields.UTF8JSONField(blank=True, default=dict, help_text='JSON format', verbose_name='data contents'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='data',
            field=miller.fields.UTF8JSONField(blank=True, default=dict, help_text='JSON format', verbose_name='data contents'),
        ),
    ]
