# Generated by Django 3.0.7 on 2020-06-08 18:14

from django.db import migrations, models
import miller.utils.models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0006_auto_20200608_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='short_url',
            field=models.CharField(blank=True, db_index=True, default=miller.utils.models.create_short_url, max_length=22, unique=True),
        ),
    ]
