# -*- coding: utf-8 -*-
# Add pg_trigram extension. This requires PostgresQL user to be superuser
# `ALTER USER resume WITH SUPERUSER;`
# and DO NOT FORGET TO user role when the migration is done.
# `ALTER USER myuser WITH NOSUPERUSER`
# Generated by Django 3.0.7 on 2020-06-10 07:27
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0009_auto_20200610_0727'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension()
    ]
