# Generated by Django 3.0.7 on 2020-07-08 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0010_enable_postgres_search_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('to be defined', 'to be defined'), ('bibtex', 'bibtex'), ('crossref', 'bibtex'), ('video-cover', 'video interview'), ('video', 'video'), ('audio', 'audio'), ('text', 'text'), ('picture', 'picture'), ('pdf', 'pdf'), ('image', 'image'), ('photo', 'photo'), ('rich', 'rich'), ('link', 'link'), ('audiovisual', 'audiovisual'), ('entity', 'entity: see data type property')], default='to be defined', max_length=24),
        ),
    ]
