# Generated by Django 4.1.3 on 2022-11-22 09:51

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0011_auto_20200708_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='documents',
            field=models.ManyToManyField(blank=True, to='miller.document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('to be defined', 'to be defined'), ('bibtex', 'bibtex'), ('crossref', 'crossref bibtex'), ('video-cover', 'video interview'), ('video', 'video'), ('audio', 'audio'), ('text', 'text'), ('picture', 'picture'), ('pdf', 'pdf'), ('image', 'image'), ('photo', 'photo'), ('rich', 'rich'), ('link', 'link'), ('audiovisual', 'audiovisual'), ('entity', 'entity: see data type property')], default='to be defined', max_length=24),
        ),
        migrations.AddIndex(
            model_name='story',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='miller_stor_search__3dacb0_gin'),
        ),
    ]
