# Generated by Django 4.1.3 on 2024-11-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miller', '0012_alter_document_documents_alter_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, to='miller.tag'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type',
            field=models.CharField(choices=[('to be defined', 'to be defined'), ('bibtex', 'bibtex'), ('crossref', 'crossref bibtex'), ('video-cover', 'video interview'), ('video', 'video'), ('audio', 'audio'), ('text', 'text'), ('picture', 'picture'), ('pdf', 'pdf'), ('image', 'image'), ('photo', 'photo'), ('rich', 'rich'), ('link', 'link'), ('audiovisual', 'audiovisual'), ('glossary', 'glossary entry'), ('entity', 'entity: see data type property')], default='to be defined', max_length=24),
        ),
    ]
